### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [MTsuji214/quotes#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by MTsuji214** [comment]
Hi, 
I got <meta name="viewport" content="width=device-width, initial-scale=1"> from CSS Tricks. I put it in the application.html.erb file right after <body>. Is that correct? And should I make those changes to Heroku as well? 
Thanks!

**Comment by BillyMassey** [comment]
Hey Mai-

Your mobile tag is correct, but I suggest placing it in the head tag instead of the body tag of application.html.erb

 Once you've done that, push it live on Heroku and check out your quote generator on your phone :)

**Comment by MTsuji214** [comment]
Got it thank you!

**Comment by BillyMassey** [comment]
Good stuff!
